### ISSUE TITLE
Create empty application

### ISSUE THREAD

**Issue by Kerego** [EliodorPopov/ACoin#2]

**Comment by EliodorPopov** [comment]
Added empty Application to master.

**Comment by Kerego** [comment]
Please to not commit directly to master, every change should be on separate branch and pull request with review.
This one in particular, is missing the gitignore file, and there is a possibility that unwanted artifacts are in the repository now,
I've created a task #11 to fix this. before you do make sure you have all the changes are commited [example](http://www.codeblocq.com/2016/01/Untrack-files-already-added-to-git-repository-based-on-gitignore/)
